version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1999
      - POSTGRES_DB=BikeService

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8000:8080

  bikeservice:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - 9090:9090
    environment:
      - datasource.driver=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/BikeService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1999
      - spring.jpa.generate-ddl=true
      - spring.thymeleaf.check-template-location=true
      - spring.thymeleaf.prefix=/WEB-INF/views/
      - spring.thymeleaf.suffix=.html
      - spring.thymeleaf.encoding=UTF-8
      - spring.thymeleaf.cache=false
      - logging.level.root=INFO
      - logging.logback.rollingpolicy.max-file-size=5MB
      - logging.logback.rollingpolicy.max-history=25
      - logging.file.path=LOGs
      - upload.path=C:\\Users\\Techn\\Documents\\JavaProjects\\BikeServiceStuff\\bikeService\\src\\main\\resources\\IMG

