version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
#      Windows:
      - ../pgdata:/var/lib/postgresql/data
#      Linux:
#      - /home/technic47/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1999
      - POSTGRES_DB=BikeService

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8000"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: technic47@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 5*!zGa7f
    ports:
      - "5050:80"


  bikeservice:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
#      Windows:
      - ../images:/app/IMG
#      Linux:
#      - /home/technic47/images:/app/IMG
    environment:
      - spring.config.location=classpath:/application-prod.properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/BikeService