version: '3.1'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: postgres
    restart: always
    container_name: db
    depends_on:
      - kafka
    ports:
      - "5555:5432"
    volumes:
#      Windows:
      - ../pgdata:/var/lib/postgresql/data
#      Linux:
#      - /home/technic47/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1999
      - POSTGRES_DB=BikeService

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: technic47@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 5*!zGa7f
    ports:
      - "5050:80"

  bikeservice:
    build:
      context: .
    container_name: app_V1.5
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
#      Windows:
      - ../images:/app/IMG
#      Linux:
#      - /home/technic47/images:/app/IMG
    env_file:
      - ../.env

  pdf_module:
    build:
      context: ./PdfModule/
    container_name: pdf_V1
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - ../.env