version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1999
      - POSTGRES_DB=BikeService

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8080"

  bikeservice:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
#      - spring.profiles.active=prod
      - datasource.driver=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/BikeService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1999
      - spring.jpa.generate-ddl=true
      - spring.thymeleaf.check-template-location=true
      - spring.thymeleaf.prefix=/WEB-INF/views/
      - spring.thymeleaf.suffix=.html
      - spring.thymeleaf.encoding=UTF-8
      - spring.thymeleaf.cache=false
      - logging.level.root=INFO
      - logging.logback.rollingpolicy.max-file-size=5MB
      - logging.logback.rollingpolicy.max-history=25
      - logging.file.path=LOGs
      - upload.path=C:\\Users\\Techn\\Documents\\JavaProjects\\BikeServiceStuff\\bikeService\\src\\main\\resources\\IMG

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    depends_on:
#      - db
#    restart: always
#    ports:
#      - "9000:9000"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=technic47@gmail.com
#      - PGADMIN_DEFAULT_PASSWORD=1999
#      - PGADMIN_LISTEN_PORT=9000