TRUNCATE
    users RESTART IDENTITY CASCADE;
TRUNCATE
    pictures RESTART IDENTITY CASCADE;
TRUNCATE
    documents RESTART IDENTITY CASCADE;
TRUNCATE
    consumables RESTART IDENTITY CASCADE;
TRUNCATE
    fasteners RESTART IDENTITY CASCADE;
TRUNCATE
    manufacturers RESTART IDENTITY CASCADE;
TRUNCATE
    tools RESTART IDENTITY CASCADE;
TRUNCATE
    parts RESTART IDENTITY CASCADE;
TRUNCATE
    bikes RESTART IDENTITY CASCADE;
TRUNCATE
    part_item RESTART IDENTITY CASCADE;
TRUNCATE
    bike_part RESTART IDENTITY CASCADE;
TRUNCATE
    user_role RESTART IDENTITY CASCADE;
TRUNCATE
    user_item RESTART IDENTITY CASCADE;